name: Upload Resume Website

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          aws-access-key-id: ${{ secrets. AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets. AWS_ACCESS_SECRET }}
          aws-region: ap-southeast-2


      - name: Deploy static site content to S3 bucket
        run: aws s3 sync s3://${{ secrets.AWS__BUCKET_NAME }} --acl public-read --follow-symlinks --size-only --delete