name: Upload Resume Website


on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::267369363118:role/Github
          aws-region: ap-southeast-2

      - name: Deploy static site content to S3 bucket
        run: aws s3 sync s3://${{ secrets.AWS__BUCKET_NAME }} --acl public-read --follow-symlinks --size-only --delete