name: Upload Resume Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2

      - name: Deploy static site content to S3 bucket
        run: aws s3 sync . s3://${{ secrets.AWS__BUCKET_NAME }} ${{secrets.AWS_ACCESS_KEY}} ${{secrets.AWS_ACCESS_SECRET}} --acl public-read --follow-symlinks --size-only --delete